name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_EMAIL: ${{ secrets.GCP_EMAIL }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: [image name]
  SERVICE: [service name]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "276.0.0"
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}

      # Set the gcloud project (required for `gcloud run deploy`)
      - run: |
          gcloud config set project $GCP_PROJECT

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          docker build -t gcr.io/"$GCP_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA

      # Deploy service to Cloud Run
      - name: Deploy service to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
          --image "gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA" \
          --region "$GCP_REGION" \
          --platform managed \
          --allow-unauthenticated
